name: packaging

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  package:
    # We use a particular version of the distribution because we want to install
    # a particular version of Docker.
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { os: 'debian', dist: 'stretch' }
          - { os: 'debian', dist: 'buster' }
          - { os: 'debian', dist: 'bullseye' }
          - { os: 'el', dist: '7' }
          - { os: 'el', dist: '8' }
          - { os: 'fedora', dist: '30' }
          - { os: 'fedora', dist: '31' }
          - { os: 'fedora', dist: '32' }
          - { os: 'fedora', dist: '33' }
          - { os: 'fedora', dist: '34' }
          - { os: 'fedora', dist: '35' }
          - { os: 'fedora', dist: '36' }
          - { os: 'ubuntu', dist: 'xenial' }
          - { os: 'ubuntu', dist: 'bionic' }
          - { os: 'ubuntu', dist: 'focal' }
          - { os: 'ubuntu', dist: 'groovy' }
          - { os: 'ubuntu', dist: 'jammy' }

    env:
      OS: ${{ matrix.platform.os }}
      DIST: ${{ matrix.platform.dist }}

    steps:
      - name: Clone the module
        uses: actions/checkout@v3
        # `actions/checkout` performs shallow clone of repo. To provide
        # proper version of the package to `packpack` we need to have
        # complete repository, otherwise it will be `0.0.1`.
        with:
          fetch-depth: 0

      - name: Clone the packpack tool
        uses: actions/checkout@v3
        with:
          repository: packpack/packpack
          path: packpack

      - name: Fetch tags
        # Found that Github checkout Actions pulls all the tags, but
        # right it deannotates the testing tag, check:
        #   https://github.com/actions/checkout/issues/290
        # But we use 'git describe ..' calls w/o '--tags' flag and it
        # prevents us from getting the needed tag for packages version
        # setup. To avoid of it, let's fetch it manually, to be sure
        # that all tags will exist always.
        run: git fetch --tags -f

        # We use a specific version of Docker because otherwise we have a problem
        # with sudoers on CentOS7.
        # See more details: https://github.com/packpack/packpack/issues/145
      - name: Reinstall Docker
        if: |
          matrix.platform.os == 'el' &&
          matrix.platform.dist == '7'
        run: |
          sudo apt-get -y purge moby-containerd* moby-engine* moby-runc*
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL ${DOCKER_URL}/gpg | sudo gpg --dearmor -o ${GPG_KEY}
          echo "deb [arch=$(dpkg --print-architecture) signed-by=${GPG_KEY}] \
              ${DOCKER_URL} $(lsb_release -cs) stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get -y install docker-ce=${DOCKER_VERSION} \
            docker-ce-cli=${DOCKER_VERSION}
        env:
          DOCKER_URL: https://download.docker.com/linux/ubuntu
          DOCKER_VERSION: 5:20.10.17~3-0~ubuntu-jammy
          GPG_KEY: /etc/apt/keyrings/docker.gpg

      - name: Create packages
        run: ./packpack/packpack

      - name: Deploy packages
        # We need this step to run only on push with tag.
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        env:
          RWS_URL_PART: https://rws.tarantool.org/tarantool-modules
          RWS_AUTH: ${{ secrets.RWS_AUTH }}
          PRODUCT_NAME: tarantool-http
        working-directory: build
        run: |
          CURL_CMD="curl -LfsS \
            -X PUT ${RWS_URL_PART}/${OS}/${DIST} \
            -u ${RWS_AUTH} \
            -F product=${PRODUCT_NAME}"
          
          shopt -s nullglob
          for f in *.deb *.rpm *.dsc *.tar.xz *.tar.gz; do
            CURL_CMD+=" -F $(basename ${f})=@${f}"
          done

          echo ${CURL_CMD}

          ${CURL_CMD}
